# Site settings
title: Northland Chartered Accountants
email: office@northlandca.co.nz
formspree: mqkodjny
url: "https://dapper-douhua-7cddaa.netlify.app"
baseurl: ""
description: "Accredited Xero experience and chartered accountancy specialising in businesses in Northland, New Zealand"
keywords: "accountancy, business advice, xero, northland, whangarei"
skills: "Accountancy services by Northlanders, for Northlanders"
meta_author: Northland Chartered Accountants
tagline: "Accountancy and business advice"
logo_url: "/assets/images/brand/logo.svg"

copyright_name: Northland Chartered Accountants
copyright_link: "/templates/content-page/"

# site_wide_alert:
#   id: 1
#   title: An example alert
#   message: This is an example of a site wide alert message with a [link](/components/site-wide-alert/).

# phase: ALPHA
# phase_link: https://github.com/FutureNorthants/LocalGovStatic/issues

livereload: true

plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-paginate

postcss:
  cache: false

paginate_path: "/blog/page:num/"
paginate: 5

permalink: pretty

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-D69JW2T64K"
    anonymize_ip: false # default

exclude:
  - LICENSE.txt
  - package-lock.json
  - package.json
  - postcss.config.js
  - README.md
  - tailwind.config.js
  - s3-cloudfront.yml
